# -*- coding: utf-8 -*-
"""checking timeseries stationary or not

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NSMz4lLiOobu_W-eu33vFMeIUyuFzqIA

kpf and ads test
"""



"""mean, varience , auto correlation doesnot change over time called stationary time seriers and centred over 0. no seanonal change.

non_stationary= not centred around particular value, and trend appears

#statistical test

#arma model expects ts to be stationary

#arima model, non_stationary, it diffrentiates non_stationary and becomes stationary

#sarima = seasonal arima model
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime as datetime
import os
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
plt.rcParams['figure.figsize'] =(10,8)
plt.rcParams['axes.grid'] = False

df =pd.read_csv('/content/drive/MyDrive/datasets/amazon_revenue_income.csv')

df.head()

def date(x):
  return datetime.datetime.strptime(x,'%m/%d/%Y')

df =pd.read_csv('/content/drive/MyDrive/datasets/amazon_revenue_income.csv', parse_dates=['Quarter'],date_parser= date)

df.head()

fig = px.line(df,x='Quarter',y='Revenue',title='Amazon revenue slider')
fig.update_xaxes(
    rangeslider_visible = True,
)
fig.show()

figure = px.line(df, x='Quarter', y='Net Income', title = 'amazon net income slider')
figure.update_xaxes(
  rangeslider_visible = True
)
figure.show()

"""#kpss test"""

from statsmodels.tsa.stattools import kpss

stats,p,lags,critical_values=kpss(df['Revenue'],'ct')

print(f'Test statistics:{stats}')
print(f'p-value: {p}')
print(f'Critical values:{critical_values}')


if p<0.05:
  print('series is not stationary')
else:
  print('series is stationary')

"""#ADf TEST"""

from statsmodels.tsa.stattools import adfuller
result = adfuller(df['Revenue'])

print(f'Test statistics :{result[0]}')
print(f'p-value :{result[1]}')
print(f'critical values : {result[4]}')


if result[1] > 0.05:
  print('ts is not stationary')
else:
  print('ts is stationary')

"""kpss has p values has less than 0.05 and also in adf test p value is more than 0.05 so it is non stationary time seris

"""







