# -*- coding: utf-8 -*-
"""timeseries_functions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSZn8DDF_kIvgtHIWZYl2PCqTDTJKJ2A
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import datetime

coindeskURL = 'https://api.coindesk.com/v1/bpi/historical/close.json'
start = datetime.date(2017,1,1)
end = datetime.date(2020,7,2)
url =f'{coindeskURL}start={start:%Y-%m-%d}&end={end:%Y-%m-%d}'
result = requests.get(url)
result.content

data = pd.read_json(result.content).iloc[:-2,:1]
data.index.name='date'
data.index = pd.to_datetime(data.index)
data

data.plot()

data.resample('Q').mean()

data.resample('Q').mean().plot()

data.resample('M').mean()

data.resample('M').mean().plot()

data.resample('D').mean()

data.resample('D').mean().plot()

data[:5]

data[:5].diff()

data[:5].diff(2)

pd.concat([data['bpi'],data['bpi'].diff(2),data['bpi'].diff()],axis=1).plot()

data[:5]

data[:5].shift()

data[:5]-data[:5].shift()

pd.concat([data,data-data.shift(),data.tshift(10)],axis=1).plot()

data.rolling(window=10).mean().plot()

data.rolling(window=10).mean().plot()
data.rolling(window=10,win_type='gaussian').sum(std=10).plot()

data.ewm(span=10).mean().plot()

pd.concat([data,data.rolling(window=10).mean(),data.ewm(span=10).mean()],axis=1).plot()

data.groupby(data.index.dayofweek).mean()

data.groupby(data.index.year).mean()

data[:5]

data[:5].cumsum()

data[:5].pct_change(2)

data[:5].expanding().sum()

data[:5].expanding().mean()

